spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/gameslists_sandro
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true